{% set name = "pytorch-lightning" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82d1c64442f043f2821b8fbe60763212712a3b1f1bc934c287d56c525420da19

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future  # >=0.17.1
    - packaging
    - numpy  >=1.16.4
    - python >=3.6
    - pyyaml  >=5.1
    - pytorch >=1.3
    - tqdm  >=4.41.0
    - tensorboard >=2.2.0
    - fsspec >=0.8.0

test:
  imports:
    - pytorch_lightning
  #commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - williamFalcon
    - borda
